# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/node/grpc/assets_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from waves import transaction_pb2 as waves_dot_transaction__pb2
from waves.node.grpc import accounts_api_pb2 as waves_dot_node_dot_grpc_dot_accounts__api__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='waves/node/grpc/assets_api.proto',
  package='waves.node.grpc',
  syntax='proto3',
  serialized_options=b'\n\032com.wavesplatform.api.grpcZCgithub.com/wavesplatform/gowaves/pkg/grpc/generated/waves/node/grpc\252\002\017Waves.Node.Grpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n waves/node/grpc/assets_api.proto\x12\x0fwaves.node.grpc\x1a\x17waves/transaction.proto\x1a\"waves/node/grpc/accounts_api.proto\" \n\x0c\x41ssetRequest\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\x0c\"D\n\nNFTRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0c\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x16\n\x0e\x61\x66ter_asset_id\x18\x03 \x01(\x0c\"W\n\x0bNFTResponse\x12\x10\n\x08\x61sset_id\x18\x01 \x01(\x0c\x12\x36\n\nasset_info\x18\x02 \x01(\x0b\x32\".waves.node.grpc.AssetInfoResponse\"\x92\x02\n\x11\x41ssetInfoResponse\x12\x0e\n\x06issuer\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x10\n\x08\x64\x65\x63imals\x18\x04 \x01(\x05\x12\x12\n\nreissuable\x18\x05 \x01(\x08\x12\x14\n\x0ctotal_volume\x18\x06 \x01(\x03\x12+\n\x06script\x18\x07 \x01(\x0b\x32\x1b.waves.node.grpc.ScriptData\x12\x13\n\x0bsponsorship\x18\x08 \x01(\x03\x12\x33\n\x11issue_transaction\x18\x0b \x01(\x0b\x32\x18.waves.SignedTransaction\x12\x17\n\x0fsponsor_balance\x18\n \x01(\x03\x32\xa4\x01\n\tAssetsApi\x12L\n\x07GetInfo\x12\x1d.waves.node.grpc.AssetRequest\x1a\".waves.node.grpc.AssetInfoResponse\x12I\n\nGetNFTList\x12\x1b.waves.node.grpc.NFTRequest\x1a\x1c.waves.node.grpc.NFTResponse0\x01\x42s\n\x1a\x63om.wavesplatform.api.grpcZCgithub.com/wavesplatform/gowaves/pkg/grpc/generated/waves/node/grpc\xaa\x02\x0fWaves.Node.Grpcb\x06proto3'
  ,
  dependencies=[waves_dot_transaction__pb2.DESCRIPTOR,waves_dot_node_dot_grpc_dot_accounts__api__pb2.DESCRIPTOR,])




_ASSETREQUEST = _descriptor.Descriptor(
  name='AssetRequest',
  full_name='waves.node.grpc.AssetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='asset_id', full_name='waves.node.grpc.AssetRequest.asset_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=146,
)


_NFTREQUEST = _descriptor.Descriptor(
  name='NFTRequest',
  full_name='waves.node.grpc.NFTRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='waves.node.grpc.NFTRequest.address', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='limit', full_name='waves.node.grpc.NFTRequest.limit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='after_asset_id', full_name='waves.node.grpc.NFTRequest.after_asset_id', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=216,
)


_NFTRESPONSE = _descriptor.Descriptor(
  name='NFTResponse',
  full_name='waves.node.grpc.NFTResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='asset_id', full_name='waves.node.grpc.NFTResponse.asset_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='asset_info', full_name='waves.node.grpc.NFTResponse.asset_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=305,
)


_ASSETINFORESPONSE = _descriptor.Descriptor(
  name='AssetInfoResponse',
  full_name='waves.node.grpc.AssetInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='issuer', full_name='waves.node.grpc.AssetInfoResponse.issuer', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='waves.node.grpc.AssetInfoResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='waves.node.grpc.AssetInfoResponse.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='decimals', full_name='waves.node.grpc.AssetInfoResponse.decimals', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reissuable', full_name='waves.node.grpc.AssetInfoResponse.reissuable', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_volume', full_name='waves.node.grpc.AssetInfoResponse.total_volume', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='script', full_name='waves.node.grpc.AssetInfoResponse.script', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sponsorship', full_name='waves.node.grpc.AssetInfoResponse.sponsorship', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='issue_transaction', full_name='waves.node.grpc.AssetInfoResponse.issue_transaction', index=8,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sponsor_balance', full_name='waves.node.grpc.AssetInfoResponse.sponsor_balance', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=308,
  serialized_end=582,
)

_NFTRESPONSE.fields_by_name['asset_info'].message_type = _ASSETINFORESPONSE
_ASSETINFORESPONSE.fields_by_name['script'].message_type = waves_dot_node_dot_grpc_dot_accounts__api__pb2._SCRIPTDATA
_ASSETINFORESPONSE.fields_by_name['issue_transaction'].message_type = waves_dot_transaction__pb2._SIGNEDTRANSACTION
DESCRIPTOR.message_types_by_name['AssetRequest'] = _ASSETREQUEST
DESCRIPTOR.message_types_by_name['NFTRequest'] = _NFTREQUEST
DESCRIPTOR.message_types_by_name['NFTResponse'] = _NFTRESPONSE
DESCRIPTOR.message_types_by_name['AssetInfoResponse'] = _ASSETINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AssetRequest = _reflection.GeneratedProtocolMessageType('AssetRequest', (_message.Message,), {
  'DESCRIPTOR' : _ASSETREQUEST,
  '__module__' : 'waves.node.grpc.assets_api_pb2'
  # @@protoc_insertion_point(class_scope:waves.node.grpc.AssetRequest)
  })
_sym_db.RegisterMessage(AssetRequest)

NFTRequest = _reflection.GeneratedProtocolMessageType('NFTRequest', (_message.Message,), {
  'DESCRIPTOR' : _NFTREQUEST,
  '__module__' : 'waves.node.grpc.assets_api_pb2'
  # @@protoc_insertion_point(class_scope:waves.node.grpc.NFTRequest)
  })
_sym_db.RegisterMessage(NFTRequest)

NFTResponse = _reflection.GeneratedProtocolMessageType('NFTResponse', (_message.Message,), {
  'DESCRIPTOR' : _NFTRESPONSE,
  '__module__' : 'waves.node.grpc.assets_api_pb2'
  # @@protoc_insertion_point(class_scope:waves.node.grpc.NFTResponse)
  })
_sym_db.RegisterMessage(NFTResponse)

AssetInfoResponse = _reflection.GeneratedProtocolMessageType('AssetInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _ASSETINFORESPONSE,
  '__module__' : 'waves.node.grpc.assets_api_pb2'
  # @@protoc_insertion_point(class_scope:waves.node.grpc.AssetInfoResponse)
  })
_sym_db.RegisterMessage(AssetInfoResponse)


DESCRIPTOR._options = None

_ASSETSAPI = _descriptor.ServiceDescriptor(
  name='AssetsApi',
  full_name='waves.node.grpc.AssetsApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=585,
  serialized_end=749,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetInfo',
    full_name='waves.node.grpc.AssetsApi.GetInfo',
    index=0,
    containing_service=None,
    input_type=_ASSETREQUEST,
    output_type=_ASSETINFORESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetNFTList',
    full_name='waves.node.grpc.AssetsApi.GetNFTList',
    index=1,
    containing_service=None,
    input_type=_NFTREQUEST,
    output_type=_NFTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ASSETSAPI)

DESCRIPTOR.services_by_name['AssetsApi'] = _ASSETSAPI

# @@protoc_insertion_point(module_scope)
