# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/node/grpc/blocks_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from waves import block_pb2 as waves_dot_block__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='waves/node/grpc/blocks_api.proto',
  package='waves.node.grpc',
  syntax='proto3',
  serialized_options=b'\n\032com.wavesplatform.api.grpcZCgithub.com/wavesplatform/gowaves/pkg/grpc/generated/waves/node/grpc\252\002\017Waves.Node.Grpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n waves/node/grpc/blocks_api.proto\x12\x0fwaves.node.grpc\x1a\x11waves/block.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"]\n\x0c\x42lockRequest\x12\x12\n\x08\x62lock_id\x18\x01 \x01(\x0cH\x00\x12\x10\n\x06height\x18\x02 \x01(\x05H\x00\x12\x1c\n\x14include_transactions\x18\x64 \x01(\x08\x42\t\n\x07request\"\xa0\x01\n\x11\x42lockRangeRequest\x12\x13\n\x0b\x66rom_height\x18\x01 \x01(\r\x12\x11\n\tto_height\x18\x02 \x01(\r\x12\x1e\n\x14generator_public_key\x18\x03 \x01(\x0cH\x00\x12\x1b\n\x11generator_address\x18\x04 \x01(\x0cH\x00\x12\x1c\n\x14include_transactions\x18\x64 \x01(\x08\x42\x08\n\x06\x66ilter\">\n\x0f\x42lockWithHeight\x12\x1b\n\x05\x62lock\x18\x01 \x01(\x0b\x32\x0c.waves.Block\x12\x0e\n\x06height\x18\x02 \x01(\r2\xfb\x01\n\tBlocksApi\x12K\n\x08GetBlock\x12\x1d.waves.node.grpc.BlockRequest\x1a .waves.node.grpc.BlockWithHeight\x12W\n\rGetBlockRange\x12\".waves.node.grpc.BlockRangeRequest\x1a .waves.node.grpc.BlockWithHeight0\x01\x12H\n\x10GetCurrentHeight\x12\x16.google.protobuf.Empty\x1a\x1c.google.protobuf.UInt32ValueBs\n\x1a\x63om.wavesplatform.api.grpcZCgithub.com/wavesplatform/gowaves/pkg/grpc/generated/waves/node/grpc\xaa\x02\x0fWaves.Node.Grpcb\x06proto3'
  ,
  dependencies=[waves_dot_block__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_BLOCKREQUEST = _descriptor.Descriptor(
  name='BlockRequest',
  full_name='waves.node.grpc.BlockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='block_id', full_name='waves.node.grpc.BlockRequest.block_id', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='waves.node.grpc.BlockRequest.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='include_transactions', full_name='waves.node.grpc.BlockRequest.include_transactions', index=2,
      number=100, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='waves.node.grpc.BlockRequest.request',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=133,
  serialized_end=226,
)


_BLOCKRANGEREQUEST = _descriptor.Descriptor(
  name='BlockRangeRequest',
  full_name='waves.node.grpc.BlockRangeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_height', full_name='waves.node.grpc.BlockRangeRequest.from_height', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='to_height', full_name='waves.node.grpc.BlockRangeRequest.to_height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='generator_public_key', full_name='waves.node.grpc.BlockRangeRequest.generator_public_key', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='generator_address', full_name='waves.node.grpc.BlockRangeRequest.generator_address', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='include_transactions', full_name='waves.node.grpc.BlockRangeRequest.include_transactions', index=4,
      number=100, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='filter', full_name='waves.node.grpc.BlockRangeRequest.filter',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=229,
  serialized_end=389,
)


_BLOCKWITHHEIGHT = _descriptor.Descriptor(
  name='BlockWithHeight',
  full_name='waves.node.grpc.BlockWithHeight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='block', full_name='waves.node.grpc.BlockWithHeight.block', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='waves.node.grpc.BlockWithHeight.height', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=391,
  serialized_end=453,
)

_BLOCKREQUEST.oneofs_by_name['request'].fields.append(
  _BLOCKREQUEST.fields_by_name['block_id'])
_BLOCKREQUEST.fields_by_name['block_id'].containing_oneof = _BLOCKREQUEST.oneofs_by_name['request']
_BLOCKREQUEST.oneofs_by_name['request'].fields.append(
  _BLOCKREQUEST.fields_by_name['height'])
_BLOCKREQUEST.fields_by_name['height'].containing_oneof = _BLOCKREQUEST.oneofs_by_name['request']
_BLOCKRANGEREQUEST.oneofs_by_name['filter'].fields.append(
  _BLOCKRANGEREQUEST.fields_by_name['generator_public_key'])
_BLOCKRANGEREQUEST.fields_by_name['generator_public_key'].containing_oneof = _BLOCKRANGEREQUEST.oneofs_by_name['filter']
_BLOCKRANGEREQUEST.oneofs_by_name['filter'].fields.append(
  _BLOCKRANGEREQUEST.fields_by_name['generator_address'])
_BLOCKRANGEREQUEST.fields_by_name['generator_address'].containing_oneof = _BLOCKRANGEREQUEST.oneofs_by_name['filter']
_BLOCKWITHHEIGHT.fields_by_name['block'].message_type = waves_dot_block__pb2._BLOCK
DESCRIPTOR.message_types_by_name['BlockRequest'] = _BLOCKREQUEST
DESCRIPTOR.message_types_by_name['BlockRangeRequest'] = _BLOCKRANGEREQUEST
DESCRIPTOR.message_types_by_name['BlockWithHeight'] = _BLOCKWITHHEIGHT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BlockRequest = _reflection.GeneratedProtocolMessageType('BlockRequest', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKREQUEST,
  '__module__' : 'waves.node.grpc.blocks_api_pb2'
  # @@protoc_insertion_point(class_scope:waves.node.grpc.BlockRequest)
  })
_sym_db.RegisterMessage(BlockRequest)

BlockRangeRequest = _reflection.GeneratedProtocolMessageType('BlockRangeRequest', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKRANGEREQUEST,
  '__module__' : 'waves.node.grpc.blocks_api_pb2'
  # @@protoc_insertion_point(class_scope:waves.node.grpc.BlockRangeRequest)
  })
_sym_db.RegisterMessage(BlockRangeRequest)

BlockWithHeight = _reflection.GeneratedProtocolMessageType('BlockWithHeight', (_message.Message,), {
  'DESCRIPTOR' : _BLOCKWITHHEIGHT,
  '__module__' : 'waves.node.grpc.blocks_api_pb2'
  # @@protoc_insertion_point(class_scope:waves.node.grpc.BlockWithHeight)
  })
_sym_db.RegisterMessage(BlockWithHeight)


DESCRIPTOR._options = None

_BLOCKSAPI = _descriptor.ServiceDescriptor(
  name='BlocksApi',
  full_name='waves.node.grpc.BlocksApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=456,
  serialized_end=707,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetBlock',
    full_name='waves.node.grpc.BlocksApi.GetBlock',
    index=0,
    containing_service=None,
    input_type=_BLOCKREQUEST,
    output_type=_BLOCKWITHHEIGHT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBlockRange',
    full_name='waves.node.grpc.BlocksApi.GetBlockRange',
    index=1,
    containing_service=None,
    input_type=_BLOCKRANGEREQUEST,
    output_type=_BLOCKWITHHEIGHT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetCurrentHeight',
    full_name='waves.node.grpc.BlocksApi.GetCurrentHeight',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=google_dot_protobuf_dot_wrappers__pb2._UINT32VALUE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLOCKSAPI)

DESCRIPTOR.services_by_name['BlocksApi'] = _BLOCKSAPI

# @@protoc_insertion_point(module_scope)
