# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/node/grpc/blockchain_api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='waves/node/grpc/blockchain_api.proto',
  package='waves.node.grpc',
  syntax='proto3',
  serialized_options=b'\n\032com.wavesplatform.api.grpcZCgithub.com/wavesplatform/gowaves/pkg/grpc/generated/waves/node/grpc\252\002\017Waves.Node.Grpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n$waves/node/grpc/blockchain_api.proto\x12\x0fwaves.node.grpc\x1a\x1bgoogle/protobuf/empty.proto\")\n\x17\x41\x63tivationStatusRequest\x12\x0e\n\x06height\x18\x01 \x01(\x05\"\xad\x01\n\x18\x41\x63tivationStatusResponse\x12\x0e\n\x06height\x18\x01 \x01(\x05\x12\x17\n\x0fvoting_interval\x18\x02 \x01(\x05\x12\x18\n\x10voting_threshold\x18\x03 \x01(\x05\x12\x12\n\nnext_check\x18\x04 \x01(\x05\x12:\n\x08\x66\x65\x61tures\x18\x05 \x03(\x0b\x32(.waves.node.grpc.FeatureActivationStatus\"\xab\x03\n\x17\x46\x65\x61tureActivationStatus\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12[\n\x11\x62lockchain_status\x18\x03 \x01(\x0e\x32@.waves.node.grpc.FeatureActivationStatus.BlockchainFeatureStatus\x12O\n\x0bnode_status\x18\x04 \x01(\x0e\x32:.waves.node.grpc.FeatureActivationStatus.NodeFeatureStatus\x12\x19\n\x11\x61\x63tivation_height\x18\x05 \x01(\x05\x12\x19\n\x11supporting_blocks\x18\x06 \x01(\x05\"E\n\x17\x42lockchainFeatureStatus\x12\r\n\tUNDEFINED\x10\x00\x12\x0c\n\x08\x41PPROVED\x10\x01\x12\r\n\tACTIVATED\x10\x02\"D\n\x11NodeFeatureStatus\x12\x13\n\x0fNOT_IMPLEMENTED\x10\x00\x12\x0f\n\x0bIMPLEMENTED\x10\x01\x12\t\n\x05VOTED\x10\x02\")\n\x12\x42\x61seTargetResponse\x12\x13\n\x0b\x62\x61se_target\x18\x01 \x01(\x03\"\x1e\n\rScoreResponse\x12\r\n\x05score\x18\x01 \x01(\x0c\x32\x97\x02\n\rBlockchainApi\x12j\n\x13GetActivationStatus\x12(.waves.node.grpc.ActivationStatusRequest\x1a).waves.node.grpc.ActivationStatusResponse\x12L\n\rGetBaseTarget\x12\x16.google.protobuf.Empty\x1a#.waves.node.grpc.BaseTargetResponse\x12L\n\x12GetCumulativeScore\x12\x16.google.protobuf.Empty\x1a\x1e.waves.node.grpc.ScoreResponseBs\n\x1a\x63om.wavesplatform.api.grpcZCgithub.com/wavesplatform/gowaves/pkg/grpc/generated/waves/node/grpc\xaa\x02\x0fWaves.Node.Grpcb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_FEATUREACTIVATIONSTATUS_BLOCKCHAINFEATURESTATUS = _descriptor.EnumDescriptor(
  name='BlockchainFeatureStatus',
  full_name='waves.node.grpc.FeatureActivationStatus.BlockchainFeatureStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNDEFINED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='APPROVED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACTIVATED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=594,
  serialized_end=663,
)
_sym_db.RegisterEnumDescriptor(_FEATUREACTIVATIONSTATUS_BLOCKCHAINFEATURESTATUS)

_FEATUREACTIVATIONSTATUS_NODEFEATURESTATUS = _descriptor.EnumDescriptor(
  name='NodeFeatureStatus',
  full_name='waves.node.grpc.FeatureActivationStatus.NodeFeatureStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOT_IMPLEMENTED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='IMPLEMENTED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='VOTED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=665,
  serialized_end=733,
)
_sym_db.RegisterEnumDescriptor(_FEATUREACTIVATIONSTATUS_NODEFEATURESTATUS)


_ACTIVATIONSTATUSREQUEST = _descriptor.Descriptor(
  name='ActivationStatusRequest',
  full_name='waves.node.grpc.ActivationStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='waves.node.grpc.ActivationStatusRequest.height', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=127,
)


_ACTIVATIONSTATUSRESPONSE = _descriptor.Descriptor(
  name='ActivationStatusResponse',
  full_name='waves.node.grpc.ActivationStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='waves.node.grpc.ActivationStatusResponse.height', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voting_interval', full_name='waves.node.grpc.ActivationStatusResponse.voting_interval', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voting_threshold', full_name='waves.node.grpc.ActivationStatusResponse.voting_threshold', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='next_check', full_name='waves.node.grpc.ActivationStatusResponse.next_check', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='features', full_name='waves.node.grpc.ActivationStatusResponse.features', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=303,
)


_FEATUREACTIVATIONSTATUS = _descriptor.Descriptor(
  name='FeatureActivationStatus',
  full_name='waves.node.grpc.FeatureActivationStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='waves.node.grpc.FeatureActivationStatus.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='waves.node.grpc.FeatureActivationStatus.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='blockchain_status', full_name='waves.node.grpc.FeatureActivationStatus.blockchain_status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_status', full_name='waves.node.grpc.FeatureActivationStatus.node_status', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='activation_height', full_name='waves.node.grpc.FeatureActivationStatus.activation_height', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='supporting_blocks', full_name='waves.node.grpc.FeatureActivationStatus.supporting_blocks', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FEATUREACTIVATIONSTATUS_BLOCKCHAINFEATURESTATUS,
    _FEATUREACTIVATIONSTATUS_NODEFEATURESTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=306,
  serialized_end=733,
)


_BASETARGETRESPONSE = _descriptor.Descriptor(
  name='BaseTargetResponse',
  full_name='waves.node.grpc.BaseTargetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_target', full_name='waves.node.grpc.BaseTargetResponse.base_target', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=735,
  serialized_end=776,
)


_SCORERESPONSE = _descriptor.Descriptor(
  name='ScoreResponse',
  full_name='waves.node.grpc.ScoreResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='waves.node.grpc.ScoreResponse.score', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=778,
  serialized_end=808,
)

_ACTIVATIONSTATUSRESPONSE.fields_by_name['features'].message_type = _FEATUREACTIVATIONSTATUS
_FEATUREACTIVATIONSTATUS.fields_by_name['blockchain_status'].enum_type = _FEATUREACTIVATIONSTATUS_BLOCKCHAINFEATURESTATUS
_FEATUREACTIVATIONSTATUS.fields_by_name['node_status'].enum_type = _FEATUREACTIVATIONSTATUS_NODEFEATURESTATUS
_FEATUREACTIVATIONSTATUS_BLOCKCHAINFEATURESTATUS.containing_type = _FEATUREACTIVATIONSTATUS
_FEATUREACTIVATIONSTATUS_NODEFEATURESTATUS.containing_type = _FEATUREACTIVATIONSTATUS
DESCRIPTOR.message_types_by_name['ActivationStatusRequest'] = _ACTIVATIONSTATUSREQUEST
DESCRIPTOR.message_types_by_name['ActivationStatusResponse'] = _ACTIVATIONSTATUSRESPONSE
DESCRIPTOR.message_types_by_name['FeatureActivationStatus'] = _FEATUREACTIVATIONSTATUS
DESCRIPTOR.message_types_by_name['BaseTargetResponse'] = _BASETARGETRESPONSE
DESCRIPTOR.message_types_by_name['ScoreResponse'] = _SCORERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActivationStatusRequest = _reflection.GeneratedProtocolMessageType('ActivationStatusRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVATIONSTATUSREQUEST,
  '__module__' : 'waves.node.grpc.blockchain_api_pb2'
  # @@protoc_insertion_point(class_scope:waves.node.grpc.ActivationStatusRequest)
  })
_sym_db.RegisterMessage(ActivationStatusRequest)

ActivationStatusResponse = _reflection.GeneratedProtocolMessageType('ActivationStatusResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACTIVATIONSTATUSRESPONSE,
  '__module__' : 'waves.node.grpc.blockchain_api_pb2'
  # @@protoc_insertion_point(class_scope:waves.node.grpc.ActivationStatusResponse)
  })
_sym_db.RegisterMessage(ActivationStatusResponse)

FeatureActivationStatus = _reflection.GeneratedProtocolMessageType('FeatureActivationStatus', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREACTIVATIONSTATUS,
  '__module__' : 'waves.node.grpc.blockchain_api_pb2'
  # @@protoc_insertion_point(class_scope:waves.node.grpc.FeatureActivationStatus)
  })
_sym_db.RegisterMessage(FeatureActivationStatus)

BaseTargetResponse = _reflection.GeneratedProtocolMessageType('BaseTargetResponse', (_message.Message,), {
  'DESCRIPTOR' : _BASETARGETRESPONSE,
  '__module__' : 'waves.node.grpc.blockchain_api_pb2'
  # @@protoc_insertion_point(class_scope:waves.node.grpc.BaseTargetResponse)
  })
_sym_db.RegisterMessage(BaseTargetResponse)

ScoreResponse = _reflection.GeneratedProtocolMessageType('ScoreResponse', (_message.Message,), {
  'DESCRIPTOR' : _SCORERESPONSE,
  '__module__' : 'waves.node.grpc.blockchain_api_pb2'
  # @@protoc_insertion_point(class_scope:waves.node.grpc.ScoreResponse)
  })
_sym_db.RegisterMessage(ScoreResponse)


DESCRIPTOR._options = None

_BLOCKCHAINAPI = _descriptor.ServiceDescriptor(
  name='BlockchainApi',
  full_name='waves.node.grpc.BlockchainApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=811,
  serialized_end=1090,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetActivationStatus',
    full_name='waves.node.grpc.BlockchainApi.GetActivationStatus',
    index=0,
    containing_service=None,
    input_type=_ACTIVATIONSTATUSREQUEST,
    output_type=_ACTIVATIONSTATUSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetBaseTarget',
    full_name='waves.node.grpc.BlockchainApi.GetBaseTarget',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_BASETARGETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetCumulativeScore',
    full_name='waves.node.grpc.BlockchainApi.GetCumulativeScore',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_SCORERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BLOCKCHAINAPI)

DESCRIPTOR.services_by_name['BlockchainApi'] = _BLOCKCHAINAPI

# @@protoc_insertion_point(module_scope)
