# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/block.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from waves import transaction_pb2 as waves_dot_transaction__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='waves/block.proto',
  package='waves',
  syntax='proto3',
  serialized_options=b'\n com.wavesplatform.protobuf.blockZ9github.com/wavesplatform/gowaves/pkg/grpc/generated/waves\252\002\005Waves',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11waves/block.proto\x12\x05waves\x1a\x17waves/transaction.proto\"\xd0\x02\n\x05\x42lock\x12#\n\x06header\x18\x01 \x01(\x0b\x32\x13.waves.Block.Header\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12.\n\x0ctransactions\x18\x03 \x03(\x0b\x32\x18.waves.SignedTransaction\x1a\xde\x01\n\x06Header\x12\x10\n\x08\x63hain_id\x18\x01 \x01(\x05\x12\x11\n\treference\x18\x02 \x01(\x0c\x12\x13\n\x0b\x62\x61se_target\x18\x03 \x01(\x03\x12\x1c\n\x14generation_signature\x18\x04 \x01(\x0c\x12\x15\n\rfeature_votes\x18\x05 \x03(\r\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\x12\x0f\n\x07version\x18\x07 \x01(\x05\x12\x11\n\tgenerator\x18\x08 \x01(\x0c\x12\x13\n\x0breward_vote\x18\t \x01(\x03\x12\x19\n\x11transactions_root\x18\n \x01(\x0c\"\x9c\x01\n\nMicroBlock\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x11\n\treference\x18\x02 \x01(\x0c\x12\x1f\n\x17updated_block_signature\x18\x03 \x01(\x0c\x12\x19\n\x11sender_public_key\x18\x04 \x01(\x0c\x12.\n\x0ctransactions\x18\x05 \x03(\x0b\x32\x18.waves.SignedTransaction\"e\n\x10SignedMicroBlock\x12&\n\x0bmicro_block\x18\x01 \x01(\x0b\x32\x11.waves.MicroBlock\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x12\x16\n\x0etotal_block_id\x18\x03 \x01(\x0c\x42\x65\n com.wavesplatform.protobuf.blockZ9github.com/wavesplatform/gowaves/pkg/grpc/generated/waves\xaa\x02\x05Wavesb\x06proto3'
  ,
  dependencies=[waves_dot_transaction__pb2.DESCRIPTOR,])




_BLOCK_HEADER = _descriptor.Descriptor(
  name='Header',
  full_name='waves.Block.Header',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chain_id', full_name='waves.Block.Header.chain_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reference', full_name='waves.Block.Header.reference', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='base_target', full_name='waves.Block.Header.base_target', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='generation_signature', full_name='waves.Block.Header.generation_signature', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='feature_votes', full_name='waves.Block.Header.feature_votes', index=4,
      number=5, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='waves.Block.Header.timestamp', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='waves.Block.Header.version', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='generator', full_name='waves.Block.Header.generator', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reward_vote', full_name='waves.Block.Header.reward_vote', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transactions_root', full_name='waves.Block.Header.transactions_root', index=9,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=390,
)

_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='waves.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='waves.Block.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='waves.Block.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transactions', full_name='waves.Block.transactions', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_BLOCK_HEADER, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=390,
)


_MICROBLOCK = _descriptor.Descriptor(
  name='MicroBlock',
  full_name='waves.MicroBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='waves.MicroBlock.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reference', full_name='waves.MicroBlock.reference', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updated_block_signature', full_name='waves.MicroBlock.updated_block_signature', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender_public_key', full_name='waves.MicroBlock.sender_public_key', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transactions', full_name='waves.MicroBlock.transactions', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=549,
)


_SIGNEDMICROBLOCK = _descriptor.Descriptor(
  name='SignedMicroBlock',
  full_name='waves.SignedMicroBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='micro_block', full_name='waves.SignedMicroBlock.micro_block', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='signature', full_name='waves.SignedMicroBlock.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total_block_id', full_name='waves.SignedMicroBlock.total_block_id', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=551,
  serialized_end=652,
)

_BLOCK_HEADER.containing_type = _BLOCK
_BLOCK.fields_by_name['header'].message_type = _BLOCK_HEADER
_BLOCK.fields_by_name['transactions'].message_type = waves_dot_transaction__pb2._SIGNEDTRANSACTION
_MICROBLOCK.fields_by_name['transactions'].message_type = waves_dot_transaction__pb2._SIGNEDTRANSACTION
_SIGNEDMICROBLOCK.fields_by_name['micro_block'].message_type = _MICROBLOCK
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
DESCRIPTOR.message_types_by_name['MicroBlock'] = _MICROBLOCK
DESCRIPTOR.message_types_by_name['SignedMicroBlock'] = _SIGNEDMICROBLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), {

  'Header' : _reflection.GeneratedProtocolMessageType('Header', (_message.Message,), {
    'DESCRIPTOR' : _BLOCK_HEADER,
    '__module__' : 'waves.block_pb2'
    # @@protoc_insertion_point(class_scope:waves.Block.Header)
    })
  ,
  'DESCRIPTOR' : _BLOCK,
  '__module__' : 'waves.block_pb2'
  # @@protoc_insertion_point(class_scope:waves.Block)
  })
_sym_db.RegisterMessage(Block)
_sym_db.RegisterMessage(Block.Header)

MicroBlock = _reflection.GeneratedProtocolMessageType('MicroBlock', (_message.Message,), {
  'DESCRIPTOR' : _MICROBLOCK,
  '__module__' : 'waves.block_pb2'
  # @@protoc_insertion_point(class_scope:waves.MicroBlock)
  })
_sym_db.RegisterMessage(MicroBlock)

SignedMicroBlock = _reflection.GeneratedProtocolMessageType('SignedMicroBlock', (_message.Message,), {
  'DESCRIPTOR' : _SIGNEDMICROBLOCK,
  '__module__' : 'waves.block_pb2'
  # @@protoc_insertion_point(class_scope:waves.SignedMicroBlock)
  })
_sym_db.RegisterMessage(SignedMicroBlock)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
