# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: waves/lang/dapp_meta.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='waves/lang/dapp_meta.proto',
  package='waves',
  syntax='proto3',
  serialized_options=b'\n\037com.wavesplatform.protobuf.dappZ8github.com/wavesplatform/gowaves/pkg/ride/meta/generated\252\002\005Waves',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1awaves/lang/dapp_meta.proto\x12\x05waves\"\xb9\x02\n\x08\x44\x41ppMeta\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x34\n\x05\x66uncs\x18\x02 \x03(\x0b\x32%.waves.DAppMeta.CallableFuncSignature\x12Z\n\"compactNameAndOriginalNamePairList\x18\x03 \x03(\x0b\x32..waves.DAppMeta.CompactNameAndOriginalNamePair\x12\x15\n\roriginalNames\x18\x04 \x03(\t\x1a&\n\x15\x43\x61llableFuncSignature\x12\r\n\x05types\x18\x01 \x01(\x0c\x1aK\n\x1e\x43ompactNameAndOriginalNamePair\x12\x13\n\x0b\x63ompactName\x18\x01 \x01(\t\x12\x14\n\x0coriginalName\x18\x02 \x01(\tBc\n\x1f\x63om.wavesplatform.protobuf.dappZ8github.com/wavesplatform/gowaves/pkg/ride/meta/generated\xaa\x02\x05Wavesb\x06proto3'
)




_DAPPMETA_CALLABLEFUNCSIGNATURE = _descriptor.Descriptor(
  name='CallableFuncSignature',
  full_name='waves.DAppMeta.CallableFuncSignature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='types', full_name='waves.DAppMeta.CallableFuncSignature.types', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=274,
)

_DAPPMETA_COMPACTNAMEANDORIGINALNAMEPAIR = _descriptor.Descriptor(
  name='CompactNameAndOriginalNamePair',
  full_name='waves.DAppMeta.CompactNameAndOriginalNamePair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='compactName', full_name='waves.DAppMeta.CompactNameAndOriginalNamePair.compactName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='originalName', full_name='waves.DAppMeta.CompactNameAndOriginalNamePair.originalName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=351,
)

_DAPPMETA = _descriptor.Descriptor(
  name='DAppMeta',
  full_name='waves.DAppMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='waves.DAppMeta.version', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='funcs', full_name='waves.DAppMeta.funcs', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='compactNameAndOriginalNamePairList', full_name='waves.DAppMeta.compactNameAndOriginalNamePairList', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='originalNames', full_name='waves.DAppMeta.originalNames', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DAPPMETA_CALLABLEFUNCSIGNATURE, _DAPPMETA_COMPACTNAMEANDORIGINALNAMEPAIR, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=351,
)

_DAPPMETA_CALLABLEFUNCSIGNATURE.containing_type = _DAPPMETA
_DAPPMETA_COMPACTNAMEANDORIGINALNAMEPAIR.containing_type = _DAPPMETA
_DAPPMETA.fields_by_name['funcs'].message_type = _DAPPMETA_CALLABLEFUNCSIGNATURE
_DAPPMETA.fields_by_name['compactNameAndOriginalNamePairList'].message_type = _DAPPMETA_COMPACTNAMEANDORIGINALNAMEPAIR
DESCRIPTOR.message_types_by_name['DAppMeta'] = _DAPPMETA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DAppMeta = _reflection.GeneratedProtocolMessageType('DAppMeta', (_message.Message,), {

  'CallableFuncSignature' : _reflection.GeneratedProtocolMessageType('CallableFuncSignature', (_message.Message,), {
    'DESCRIPTOR' : _DAPPMETA_CALLABLEFUNCSIGNATURE,
    '__module__' : 'waves.lang.dapp_meta_pb2'
    # @@protoc_insertion_point(class_scope:waves.DAppMeta.CallableFuncSignature)
    })
  ,

  'CompactNameAndOriginalNamePair' : _reflection.GeneratedProtocolMessageType('CompactNameAndOriginalNamePair', (_message.Message,), {
    'DESCRIPTOR' : _DAPPMETA_COMPACTNAMEANDORIGINALNAMEPAIR,
    '__module__' : 'waves.lang.dapp_meta_pb2'
    # @@protoc_insertion_point(class_scope:waves.DAppMeta.CompactNameAndOriginalNamePair)
    })
  ,
  'DESCRIPTOR' : _DAPPMETA,
  '__module__' : 'waves.lang.dapp_meta_pb2'
  # @@protoc_insertion_point(class_scope:waves.DAppMeta)
  })
_sym_db.RegisterMessage(DAppMeta)
_sym_db.RegisterMessage(DAppMeta.CallableFuncSignature)
_sym_db.RegisterMessage(DAppMeta.CompactNameAndOriginalNamePair)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
